### PR TITLE
Update learn chart graph with latest changes

### PR DESCRIPTION
**Pull request by ParadoxARG**
## Purpose

* Update learn chart graph with dev-next latest changes

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by marianstdt — APPROVED** [review]
looks good!

**Review by lucaasrojas — CHANGES_REQUESTED** [review]
Be careful with this gap. I've fixed this removing the right padding in the previous demo.

image

image

**Comment by ParadoxARG** [comment]
> Be careful with this gap. I've fixed this removing the right padding in the previous demo.
> 
> image
> 
> image

@lucaasrojas are you trying with my branch? This was broken on master but I see it well in this branch

**Comment by lucaasrojas** [comment]
> > Be careful with this gap. I've fixed this removing the right padding in the previous demo.
> > image
> > image
> 
> @lucaasrojas are you trying with my branch? This was broken on master but I see it well in this branch

Yes. _update-graph-changes_

**Comment by ParadoxARG** [comment]
This is a preexisting bug from dev-next. Merging changes and adding issue to the backlog.

**Pull request merged**
