### PR TITLE
Fix discovery partial view responsiveness

### PR DESCRIPTION
**Pull request by marianstdt**
## Purpose

*Fixed this:
image

Result:
image

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by ParadoxARG — CHANGES_REQUESTED** [review]
its broken from 1170-1290px wide

**Comment by kbrons** [comment]
In mobile, the icons use a full row. The initial version was done without columns because of these issues, try to do it using paddings and margins instead of bootstrap's columns. 
image

**Review by kbrons — CHANGES_REQUESTED** [review]
In mobile, the icons use a full row. The initial version was done without columns because of these issues, try to do it using paddings and margins instead of bootstrap's columns. 
image

**Comment by ParadoxARG** [comment]
Dropped

**Pull request closed without merging**
