### PR TITLE
Fix chart order

### PR DESCRIPTION
**Pull request by marianstdt**
## Purpose

* Fix chart components order

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

image

### CODE REVIEW

**Comment by ParadoxARG** [comment]
It's broken on mobile
image

**Comment by marianstdt** [comment]
> It's broken on mobile
> image

It was supposed to be a draft PR, added WIP to the title. 
thanks

**Comment by marianstdt** [comment]
Fixed mobile View @ParadoxARG could you check it?
image

**Review by ParadoxARG — APPROVED** [review]
LGTM

**Review by ParadoxARG — APPROVED** [review]

**Pull request merged**
